- name: Get facts for leaf routers
  hosts: all # all #mgmt_r1
  connection: network_cli
  vars:
    - results: "{{inventory_dir}}/results"
    - file_uptime: uptime.log
  gather_facts: True # False #True

  tasks:    
    - include: "tasks/read-{{src|default('device')}}.yml"
    - include: "tasks/report-{{dst|default('text')}}.yml"
