- name: Get facts for leaf routers
  hosts: all # all #mgmt_r1
  connection: network_cli
  vars:
    - results: results
  gather_facts: True # False #True

  tasks:
    - name: Get IOS facts
      ios_facts:
        gather_subset: hardware  #all
      register: result

    - debug: var=result

    - name: Copy to results folder
      copy:
        content: |
         {{ result.ansible_facts.ansible_net_serialnum }}
        dest: "results/{{inventory_hostname}}_Serijska_stevilka.txt"
      delegate_to: localhost   


