- name: Get facts for leaf routers
  hosts: mgmt_r1 # all #mgmt_r1
  connection: network_cli
  vars:
    - results: results
  gather_facts: True # False #True

  tasks:
    - name: Create directory with name "Results"
      file: path={{results}} state=directory
      run_once: true

    - name: Get IOS facts
      ios_facts:
        gather_subset: hardware  #all
      register: result

    - debug: var=result

    - name: Copy to results folder
      copy:
        content: |
         {{ result.ansible_facts|to_nice_yaml (indent=4) }}
        dest: "results/{{inventory_hostname}}.yml"
      delegate_to: localhost   


