- name: Get state of routers
  hosts: all # all #mgmt_r14
  connection: local

  tasks:
    - name: Include connection data variables
      include_vars:
        file: vars/device_connection_data.yml

    - include: tasks/find_error_disabled_ports.yml

