- name: Configure access-list
  ios_config:
    provider: "{{ cli }}"
    match: exact
    lines:
      #- permit ip host {{ managed_devices[item]['device_ip'] }} any
      - permit ip host 0.0.0.0 host 255.255.255.255 # Allow BOOTP Massages
      - permit ip {{ managed_devices[item]['device_network'] }} {{ managed_devices[item]['device_wildcard_mask'] }} 172.30.18.83 0.0.0.0 # ARICENT
      - permit ip {{ managed_devices[item]['device_network'] }} {{ managed_devices[item]['device_wildcard_mask'] }} 172.30.18.91 0.0.0.0 # ARICENT
      - permit ip {{ managed_devices[item]['device_network'] }} {{ managed_devices[item]['device_wildcard_mask'] }} 10.0.0.0 1.255.255.255 
    parents: ip access-list extended ACL_{{ managed_devices[item]['device_name'] }}
    before: no ip access-list extended ACL_{{ managed_devices[item]['device_name'] }}
  with_items: "{{ managed_devices }}"
  when: not managed_devices[item]['default']

- name: Configure interfaces
  ios_config:
    provider: "{{ cli }}"
    match: exact
    lines:
      - description {{ managed_devices[item]['description'] }}
      - no switchport
      - ip address {{ managed_devices[item]['device_gw'] }} {{ managed_devices[item]['device_mask'] }}
      - ip access-group ACL_{{ managed_devices[item]['device_name'] }} in
      - ip ospf 1 area 0
      - ip helper-address 11.214.41.69
    parents: interface {{ item }}
    before: default interface {{ item }}
  with_items: "{{ managed_devices }}"
  when: not managed_devices[item]['default']

- name: Enable passive interface
  ios_config:
    provider: "{{ cli }}"
    match: line
    lines:
      - passive-interface {{ item }}
    parents: router ospf 1
  with_items: "{{ managed_devices }}"
  when: not managed_devices[item]['default']

- name: Set speed on interface
  ios_config:
    provider: "{{ cli }}"
    match: line 
    lines:
      - speed {{ managed_devices[item]['speed'] }}
    parents: interface {{ item }}
  with_items: "{{ managed_devices }}"
  when: not managed_devices[item]['default'] and "speed" in managed_devices[item]